# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
# Your code here
import numpy as np
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[7,6,5],[2,3,4]])

In [3]:
A.dot(B+C)

array([[ 20,  24,  28],
       [ 48,  56,  64],
       [ 76,  88, 100]])

In [4]:
A.dot(B) + A.dot(C)

array([[ 20,  24,  28],
       [ 48,  56,  64],
       [ 76,  88, 100]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [18]:
# Your code here 
A = np.array([[1,2], [3,4]])
B = np.array([[1,2],[4,5]])
C = np.array([[4,5],[6,7]])

In [19]:
D = B.dot(C)
A.dot(D)

array([[108, 129],
       [232, 277]])

In [20]:
E = A.dot(B)
C.dot(E)

array([[131, 178],
       [187, 254]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [21]:
# Your code here 
A = np.array([[1,2], [3,4]])
B = np.array([[1,2],[4,5]])

In [22]:
A.dot(B)

array([[ 9, 12],
       [19, 26]])

In [23]:
B.dot(A)

array([[ 7, 10],
       [19, 28]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [24]:
# Your code here 
x = [1,2,3,4]
y = [5,6,3,4]


In [28]:
np.transpose(x).dot(y)

42

In [29]:
np.transpose(y).dot(x)

42

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [31]:
# Your code here 
A = np.array([[1,2], [4,5]])
B = np.array([[6,7], [3,4]])

np.transpose(A.dot(B))

array([[12, 39],
       [15, 48]])

In [33]:
np.transpose(B).dot(np.transpose(A))

array([[12, 39],
       [15, 48]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 